import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div id='about'>
          <p >
            Reprehenderit consectetur enim tempor proident eiusmod pariatur. Labore ut sunt Lorem laborum dolore tempor in elit irure veniam excepteur deserunt excepteur.
            Dolor dolore aute aliquip amet exercitation culpa sunt commodo ipsum tempor qui sit eu anim. Et adipisicing mollit tempor est.
            Voluptate minim velit exercitation laboris do nostrud enim exercitation dolor veniam exercitation laborum qui esse. Laboris ullamco ut et consectetur et ullamco. Qui sunt aliqua ut dolore qui excepteur culpa ipsum voluptate tempor.
          </p>
        </div>
        <div id='cv'>
          <p >
            Nostrud eiusmod cillum anim ad eu et anim excepteur est ut qui. Proident nostrud sint do excepteur ex ipsum do deserunt voluptate cillum aliqua in.
            Sit reprehenderit veniam Lorem laboris proident esse. Qui sunt ullamco magna proident consequat. Sint amet eiusmod consequat laborum irure ea enim pariatur.
            Mollit aliquip nostrud do aliqua id adipisicing incididunt velit.
            Quis fugiat id aliqua anim cillum est esse velit ea elit minim amet elit consequat. Eiusmod deserunt enim culpa esse tempor eu aute commodo pariatur culpa anim eu et. Duis aute exercitation in occaecat magna ad non dolore aute velit velit reprehenderit mollit. Do labore laboris ipsum sit dolore sit qui ea id quis. Ea consectetur consectetur officia esse qui sint occaecat nisi Lorem est aliquip eu est pariatur.
          </p>
        </div>
        <div id='projects'>
          <p >
            Reprehenderit consectetur enim tempor proident eiusmod pariatur. Labore ut sunt Lorem laborum dolore tempor in elit irure veniam excepteur deserunt excepteur.
            Dolor dolore aute aliquip amet exercitation culpa sunt commodo ipsum tempor qui sit eu anim. Et adipisicing mollit tempor est.
            Proident irure do non irure incididunt laboris dolor consectetur sit aute sit. Culpa aliquip laborum magna excepteur labore excepteur consequat sunt culpa sint sint tempor. Enim fugiat fugiat fugiat quis officia amet fugiat quis anim duis cupidatat reprehenderit aute. Deserunt reprehenderit ut ipsum est mollit quis magna pariatur sit. Exercitation nostrud exercitation ex veniam aute est eu consectetur eiusmod commodo deserunt ea adipisicing.
            Magna excepteur culpa excepteur pariatur commodo amet esse. Pariatur exercitation aute nostrud ea veniam velit. Non esse ex amet amet ad dolor exercitation pariatur magna Lorem commodo amet dolor ea. Consequat pariatur duis magna commodo voluptate. Do aliqua minim duis ut eiusmod consectetur. Sunt velit pariatur nisi dolore ex. Ipsum adipisicing qui voluptate pariatur do anim nostrud incididunt.
          </p>
        </div>
        <div id='contact'>
          <p >
            Laborum occaecat incididunt consectetur nostrud officia exercitation ex tempor consectetur cupidatat reprehenderit. Eiusmod ea veniam ad nisi exercitation mollit.
            Sunt ullamco quis est duis occaecat. Ea non irure fugiat laboris ex fugiat incididunt ut. Mollit dolor nulla qui cillum adipisicing ipsum eu aliquip nulla cillum occaecat.
            Minim quis id deserunt qui Lorem magna laboris anim occaecat excepteur cupidatat qui ullamco nulla.
            Voluptate nostrud occaecat nisi sit in labore. Irure et est in minim do duis. Culpa velit irure aliqua laboris consequat dolore elit aliquip reprehenderit quis.
            Aliquip culpa Lorem proident est exercitation aliquip cupidatat ad excepteur proident. Minim eu et nisi est quis minim exercitation cupidatat do. Velit consectetur ex nisi nisi elit minim adipisicing proident Lorem ipsum. Aute voluptate aliqua aliqua non.
            Fugiat commodo exercitation aliquip Lorem deserunt sunt et aliquip dolor occaecat ad nostrud fugiat. Ea proident ex veniam cillum veniam qui eu aute ex quis nostrud ad et. Commodo esse laboris culpa officia deserunt in ipsum. Nisi eu minim fugiat non proident dolor. Ea consequat eiusmod ullamco Lorem cillum culpa enim sunt eiusmod ullamco dolore ipsum duis. Ut velit exercitation magna eu incididunt voluptate aute eu Lorem esse laboris.
          </p>
        </div>
      </main>
    </div>
  )
}
